name: oda

services:

  zookeeper:
    container_name: zookeeper
    image: alebocci/odakafka
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    restart: always
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: kafka
    image: alebocci/odakafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override auto.create.topics.enable=false --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}"
    ]
    depends_on:
    - zookeeper
    ports:
    - ${kafka_port}:9094
    - ${kafka_port_static}:9095
    restart: always
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE1://${kafka_address}:9094,OUTSIDE2://${kafka_address_static}:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE1://${kafka_address}:${kafka_port},OUTSIDE2://${kafka_address_static}:${kafka_port_static}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE1:PLAINTEXT,OUTSIDE2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    env_file:
      - influx.env
    volumes:
      - influxdbdata:/var/lib/influxdb2:rw
      - influxdbconfig:/etc/influxdb2:rw
    restart: always

  dbmanager:
    build: 
      context: src/db_manager
      args:
        DB_MANAGER_PORT: ${db_manager_port}
    container_name: dbmanager
    restart: always
    env_file:
      - influx.env
    environment: 
      DB_PORT: ${db_port}
    depends_on:
      - influxdb

  topicmanager:
    build:
      context: src/topic_manager
      args:
        TOPIC_MANAGER_PORT: ${topic_manager_port}
    container_name: topicmanager
    restart: always
    environment: 
      KAFKA_INTERNAL_PORT: ${kafka_internal_port}
      RESTORE_TOPICS: ${restore_topics_from_file}
    volumes:
      - topiclist:/app/topiclist:rw
    depends_on:
      - kafka
      - dbmanager

  datapump:
    build: src/data_pump
    container_name: datapump
    restart: always
    environment: 
      KAFKA_INTERNAL_PORT: ${kafka_internal_port}
      DB_MANAGER_PORT: ${db_manager_port}
    depends_on:
      - kafka
      - dbmanager
    
  queryaggregator:
    build: 
      context: src/query_aggregator
      args:
        QUERY_AGGREGATOR_PORT: ${query_aggregator_port}
    container_name: queryaggregator
    restart: always
    environment:
      QUERY_AGGREGATOR_PORT: ${query_aggregator_port}
      DB_MANAGER_PORT: ${db_manager_port}
    depends_on:
      - dbmanager

  apigateway:
    build: 
      context: src/api_gateway
      args:
        API_GATEWAY_PORT: ${api_gateway_port}
    container_name: apigateway
    ports:
      - ${api_gateway_port}:${api_gateway_port}
    restart: always
    environment:
      API_GATEWAY_PORT: ${api_gateway_port}
      KAFKA_PORT: ${kafka_port}
      KAFKA_PORT_STATIC: ${kafka_port_static}
      KAFKA_ADDRESS: ${kafka_address}
      KAFKA_ADDRESS_STATIC: ${kafka_address_static}
      DB_MANAGER_PORT: ${db_manager_port}
      QUERY_AGGREGATOR_PORT: ${query_aggregator_port}
      TOPIC_MANAGER_PORT: ${topic_manager_port}
    
    depends_on:
      - datapump
      - topicmanager
      - queryaggregator
      - dbmanager

volumes:
  influxdbdata:
  influxdbconfig:
  topiclist: